twig:
    file_name_pattern: '*.twig'
    form_themes:
        - '@EWZRecaptcha/Form/ewz_recaptcha_widget.html.twig'
    globals:
        currencyConverter: '@App\Service\CurrencyConverter'
        stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
        stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'


when@test:
    twig:
        strict_variables: true
        